name: CI

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  cypress:
    runs-on: ubuntu-latest
    name: 'Cypress: node-16, ubuntu-latest'

    steps:
      - uses: actions/checkout@v3

      - uses: pnpm/action-setup@v2.2.4
        with:
          version: 7

      - name: Set node version to 16
        uses: actions/setup-node@v3
        with:
          node-version: 16
          # cache: pnpm

      # - name: Cache Cypress binary
      #   uses: actions/cache@v3
      #   with:
      #     path: ~/.cache/Cypress
      #     key: cypress-${{ hashFiles('**/package.json') }}

      - name: Install
        run: pnpm install

      - name: Build
        run: pnpm build

      - name: Test
        run: npx cypress run --record --key ${{ secrets.CYPRESS_KEY }}

  lint:
    runs-on: ubuntu-latest
    name: 'Lint: node-16, ubuntu-latest'

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: pnpm/action-setup@v2.2.4
        with:
          version: 7

      - name: Set node version to 16
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: pnpm

      - name: Install
        run: pnpm install

      - name: Build
        run: pnpm build

      - name: Lint
        run: pnpm lint

      - name: Check formatting
        run: pnpm format:check

      - name: Typecheck
        run: pnpm typecheck
